version: "3.9"

services:
  kanjengmami-single:
    image: fahrizalfarid/kanjeng-mami
    container_name: kanjengmami-0
    command:
      - "--api-port=1081"
      - "-a=1@127.0.0.1:8081"
      - "--join=-1"
      - "--secret-key=sEcr3t"
    ports:
      - 1081:1081
      - 8081:8081
    volumes:
      - ${HOME}/kanjengmami:/data
    restart: always
